### ISSUE TITLE
doesn't reset mappings when typing unmapped character

### ISSUE THREAD

**Issue by max397574** [Krafi2/jeskape.nvim#5]
example: I have a mapping jk to esc

I can type jsk and it escapes and deletes the `sk`

**Comment by Krafi2** [comment]
Oh it would do that, wouldn't it? The problem is that the plugin only listens to mapped keys, so the `s` doesn't get registered. I will have to rework the code to hook into key events, but I probably won't have time this week. A very dirty fix would be to map all other keys to themselves, if you need a fix now.

**Comment by max397574** [comment]
I don't need a fix now
I just wanted to let you know so you can fix it somewhen

**Comment by max397574** [comment]
Any updates on this?

**Comment by max397574** [comment]
looks like the fix could work that's sth I've though about as well (haven't tried it out yet though)

EDIT: it looks like it's fixed now
